# -*- coding: utf-8 -*-
"""ipbl1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2X7u-dGVQWcUbu4QYLG4C-o1MYIVn9j
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data=pd.read_csv("/content/drive/MyDrive/supermarket.csv")
data.head()

from google.colab import drive
drive.mount('/content/drive')

data.info()

data.isnull().sum()

data_tmp=data.drop(['gross margin percentage','Invoice ID'],axis=1)
data_tmp.head()

g_dmmy=pd.get_dummies(data_tmp['Gender'])

g_dmmy



data_tmp=pd.concat([data_tmp,g_dmmy],axis=1)
data_tmp.head()

data_tmp.columns

import datetime

data

plt.figure(figsize=(12,6))
sns.barplot(x='Product line',y='Rating',data=data_tmp)

c=pd.DataFrame(data_tmp['City'].value_counts())
c

sns.barplot(x=c.index,y=c['City'],palette='hot')

pay=pd.DataFrame(data_tmp['Payment'].value_counts())
pay

sns.barplot(x=pay.index,y=pay.Payment)

g=pd.get_dummies(data_tmp['Gender'])

g

df=pd.concat([data,g],axis=1)
df

df=df.drop(['Invoice ID','gross margin percentage'],axis=1)
df.head()

plt.figure(figsize=(12,6))
sns.barplot(x='Product line',y='Female',data=df)

plt.figure(figsize=(12,6))
sns.barplot(x='Product line',y='Male',data=df)

plt.figure(figsize=(12,6))
sns.barplot(x='Quantity',y='Male',data=df)

mem=pd.DataFrame(df['Customer type'].value_counts())
mem

plt.figure(figsize=(12,6))
sns.barplot(x='Payment',y='Male',data=df)

plt.figure(figsize=(12,6))
sns.barplot(x='Payment',y='Female',data=df)

p=pd.DataFrame(data_tmp['Product line'].value_counts())
p

fig = px.scatter(data,x='Product line',y='Rating')
fig.show()

!pip install flask-ngrok

from flask_ngrok import run_with_ngrok
from flask import Flask

app=Flask(__name__)

run_with_ngrok(app)
@app.route("/")

def index():
  return "<h2>this is first week eda</h2>"
@app.route("/get_deatails")
def get_details():
  return "<h1> this is get details page</h1>"

app.run()









